#!/bin/sh

#Powersave script optimized for a Lenovo Thinkpad T440p:
#0) Most of this script assumes that you've already installed/configured TLP as a powersaving measure.
#     If TLP can manage a setting for you, just let it.
#1) Quad-core i7,
#2) docking-station-based ethernet (hardcoded device name)
#3) wireless only enabled when on battery (handled by TLP, not here)
#4) Some CPU cores disabled on battery power
#5) USB power management is handled by a separate udev rules script

#PCI/I2C is all done through udev rules.
#T440p is apparently well-behaved with auto for all built-in PCI/I2C devices

#This script will disable some of the CPU cores when on battery, and attempts to hard-disable the
#ethernet chip to save power.
case "$1" in
	true) # Enable power saving settings on battery
	  # cpu (powersave is the default, leave that alone...
	  #      but disable most of the cores)
	  #echo 0 > /sys/devices/system/cpu/cpu2/online
	  #echo 0 > /sys/devices/system/cpu/cpu3/online
	  echo 0 > /sys/devices/system/cpu/cpu4/online
	  echo 0 > /sys/devices/system/cpu/cpu5/online
	  echo 0 > /sys/devices/system/cpu/cpu6/online
	  echo 0 > /sys/devices/system/cpu/cpu7/online

	  # kernel write mode
	  echo 5 > /proc/sys/vm/laptop_mode
	  echo 90 > /proc/sys/vm/dirty_ratio
	  echo 1 > /proc/sys/vm/dirty_background_ratio
	  echo 60000 > /proc/sys/vm/dirty_expire_centisecs
	  echo 60000 > /proc/sys/vm/dirty_writeback_centisecs

	  #Disable ethernet on battery
	  /sbin/ifconfig enp0s25 down

	  # screen powersave (leave alone)
	  #for i in /sys/class/backlight/acpi_video*/brightness; do echo 0 > $i; done
	  #xset +dpms
	  #xset dpms 0 0 120

	  #Auto-configure displays based on previously preferred settings
	  #DISPLAY=:0 /usr/bin/xrandr --auto

	  ;;
	false) # Return to default on AC power
	  # re-enable cores 2/3/4
	  #echo 1 > /sys/devices/system/cpu/cpu2/online
	  #echo 1 > /sys/devices/system/cpu/cpu3/online
	  echo 1 > /sys/devices/system/cpu/cpu4/online
	  echo 1 > /sys/devices/system/cpu/cpu5/online
	  echo 1 > /sys/devices/system/cpu/cpu6/online
	  echo 1 > /sys/devices/system/cpu/cpu7/online

	  # kernel write mode
	  echo 0 > /proc/sys/vm/laptop_mode
	  echo 30 > /proc/sys/vm/dirty_ratio
	  echo 30 > /proc/sys/vm/dirty_background_ratio
	  echo 600 > /proc/sys/vm/dirty_expire_centisecs
	  echo 600 > /proc/sys/vm/dirty_writeback_centisecs

	  systemctl restart NetworkManager

	  #Enable ethernet and WOL
	  /sbin/ifconfig enp0s25 up

	  # screen powersave
	  #for i in /sys/class/backlight/acpi_video*/brightness; do echo 9 > $i; done
	  #xset -dpms

	  #Auto-configure displays based on previously preferred settings
	  #DISPLAY=:0 /usr/bin/xrandr --auto
	  ;;
esac
exit 0
